<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Raw health data from wearables
        Schema::create('health_metrics', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->enum('metric_type', [
                'heart_rate', 'resting_heart_rate', 'hrv',
                'blood_oxygen', 'sleep_duration', 'sleep_quality',
                'steps', 'active_calories', 'resting_energy',
                'weight', 'body_fat_pct', 'blood_pressure_systolic',
                'blood_pressure_diastolic', 'body_temperature',
                'respiratory_rate', 'vo2_max', 'workout_hr_avg',
                'workout_hr_max', 'workout_calories'
            ]);
            $table->decimal('value', 10, 2);
            $table->string('unit', 20); // bpm, ms, hours, steps, kcal, %, kg, lbs
            $table->enum('source', ['apple_watch', 'google_fit', 'fitbit', 'garmin', 'oura', 'whoop', 'manual'])->default('manual');
            $table->timestamp('recorded_at');
            $table->json('metadata')->nullable(); // extra context from the device
            $table->timestamps();

            $table->index(['user_id', 'metric_type', 'recorded_at']);
            $table->index(['user_id', 'recorded_at']);
        });

        // Rolling baselines for anomaly detection
        Schema::create('health_baselines', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->enum('metric_type', [
                'heart_rate', 'resting_heart_rate', 'hrv',
                'blood_oxygen', 'sleep_duration', 'sleep_quality',
                'steps', 'active_calories', 'resting_energy',
                'weight', 'body_fat_pct', 'vo2_max'
            ]);
            $table->decimal('avg_value', 10, 2);
            $table->decimal('std_deviation', 10, 2)->nullable();
            $table->decimal('min_value', 10, 2)->nullable();
            $table->decimal('max_value', 10, 2)->nullable();
            $table->integer('sample_count')->default(0);
            $table->integer('window_days')->default(14); // rolling window
            $table->timestamp('calculated_at');
            $table->timestamps();

            $table->unique(['user_id', 'metric_type']);
        });

        // Alerts generated by AI insight engine
        Schema::create('health_alerts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('client_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('trainer_id')->constrained('users')->cascadeOnDelete();
            $table->enum('severity', ['red', 'yellow', 'green'])->default('yellow');
            $table->string('alert_type'); // overtraining, sleep_deficit, recovery_low, etc.
            $table->string('title');
            $table->text('message');
            $table->json('data_snapshot')->nullable(); // the metrics that triggered it
            $table->text('recommendation')->nullable();
            $table->boolean('acknowledged')->default(false);
            $table->timestamp('acknowledged_at')->nullable();
            $table->timestamps();

            $table->index(['trainer_id', 'acknowledged', 'severity']);
            $table->index(['client_id', 'created_at']);
        });

        // Client consent for biometric data sharing
        Schema::create('biometric_consents', function (Blueprint $table) {
            $table->id();
            $table->foreignId('client_id')->constrained('users')->cascadeOnDelete();
            $table->foreignId('trainer_id')->constrained('users')->cascadeOnDelete();
            $table->string('metric_type'); // specific metric or 'all'
            $table->boolean('consented')->default(false);
            $table->timestamp('consented_at')->nullable();
            $table->timestamp('revoked_at')->nullable();
            $table->timestamps();

            $table->unique(['client_id', 'trainer_id', 'metric_type']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('biometric_consents');
        Schema::dropIfExists('health_alerts');
        Schema::dropIfExists('health_baselines');
        Schema::dropIfExists('health_metrics');
    }
};
